/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadorareestructuracion;

import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Edgar
 */
public class PanelReestructuracion extends javax.swing.JPanel {

    /**
     * Creates new form PanelReestructuracion
     */
    public PanelReestructuracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        doctosPreviosJTextF = new javax.swing.JTextField();
        interesVeoPrevioJTextF = new javax.swing.JTextField();
        diasVencidosJTextF = new javax.swing.JTextField();
        doctoFocalJTextF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        interesVenJTextF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        diasCapitalizacionJTextF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        doctosPosterioresJTextF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        diasPagosJTextF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        diasPosterioresJTextF = new javax.swing.JTextField();
        bCalcular = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        interesVeoPosteriorJTextF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        desplegarResultadosJTA = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        tipoInteresJCB = new javax.swing.JComboBox();

        jLabel1.setText("Doctos vencidos previos FF");

        jLabel2.setText("Tasa de interés para VEO (%)");

        jLabel3.setText("Días vencido previos FF");

        jLabel4.setText("Docto de fecha focal (FF)");

        doctosPreviosJTextF.setColumns(30);
        doctosPreviosJTextF.setToolTipText("Separe los doctos mediante: diagonales (/)");
        doctosPreviosJTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctosPreviosJTextFActionPerformed(evt);
            }
        });

        interesVeoPrevioJTextF.setColumns(10);
        interesVeoPrevioJTextF.setToolTipText("Interés previo fecha focal");

        diasVencidosJTextF.setColumns(20);
        diasVencidosJTextF.setToolTipText("Separe cada día mediante: comas (,)");
        diasVencidosJTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasVencidosJTextFActionPerformed(evt);
            }
        });

        doctoFocalJTextF.setColumns(30);

        jLabel5.setText("Tasa de interés para VEN (%)");

        interesVenJTextF.setColumns(10);

        jLabel6.setText("Días de capitalización");

        diasCapitalizacionJTextF.setColumns(10);

        jLabel7.setText("Doctos vencidos posteriores FF");

        doctosPosterioresJTextF.setColumns(30);
        doctosPosterioresJTextF.setToolTipText("Separe los doctos mediante: diagonales (/)");

        jLabel8.setText("Fechas de pago (en días)");

        diasPagosJTextF.setColumns(30);
        diasPagosJTextF.setToolTipText("Separe cada día mediante: comas (,)");
        diasPagosJTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diasPagosJTextFActionPerformed(evt);
            }
        });

        jLabel9.setText("Días posteriores FF");

        diasPosterioresJTextF.setColumns(20);
        diasPosterioresJTextF.setToolTipText("Separe cada día mediante: comas (,)");

        bCalcular.setText("Calcular");
        bCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcularActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        interesVeoPosteriorJTextF.setColumns(10);
        interesVeoPosteriorJTextF.setToolTipText("Interés posterior fecha focal");

        desplegarResultadosJTA.setEditable(false);
        desplegarResultadosJTA.setColumns(20);
        desplegarResultadosJTA.setRows(5);
        desplegarResultadosJTA.setText("Visualización de datos");
        desplegarResultadosJTA.setToolTipText("");
        jScrollPane1.setViewportView(desplegarResultadosJTA);

        jLabel10.setText("Tipo de interés");

        tipoInteresJCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Exacto", "Ordinario" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doctosPreviosJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(interesVeoPrevioJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(interesVeoPosteriorJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(diasPosterioresJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(doctosPosterioresJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(interesVenJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(diasPagosJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diasVencidosJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(doctoFocalJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diasCapitalizacionJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(bCalcular)
                                .addGap(51, 51, 51)
                                .addComponent(bSalir))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(tipoInteresJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(interesVeoPrevioJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(interesVeoPosteriorJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(doctosPreviosJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(diasVencidosJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(doctoFocalJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(diasCapitalizacionJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctosPosterioresJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(diasPosterioresJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(interesVenJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(diasPagosJTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tipoInteresJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCalcular)
                    .addComponent(bSalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void diasPagosJTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasPagosJTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasPagosJTextFActionPerformed

    private void diasVencidosJTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diasVencidosJTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diasVencidosJTextFActionPerformed

    private void doctosPreviosJTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctosPreviosJTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctosPreviosJTextFActionPerformed

    private void bCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcularActionPerformed
        Reestructuracion re = new Reestructuracion(this);
    }//GEN-LAST:event_bCalcularActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCalcular;
    private javax.swing.JButton bSalir;
    private javax.swing.JTextArea desplegarResultadosJTA;
    private javax.swing.JTextField diasCapitalizacionJTextF;
    private javax.swing.JTextField diasPagosJTextF;
    private javax.swing.JTextField diasPosterioresJTextF;
    private javax.swing.JTextField diasVencidosJTextF;
    private javax.swing.JTextField doctoFocalJTextF;
    private javax.swing.JTextField doctosPosterioresJTextF;
    private javax.swing.JTextField doctosPreviosJTextF;
    private javax.swing.JTextField interesVenJTextF;
    private javax.swing.JTextField interesVeoPosteriorJTextF;
    private javax.swing.JTextField interesVeoPrevioJTextF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox tipoInteresJCB;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the desplegarResultadosJTA
     */
    public javax.swing.JTextArea getDesplegarResultadosJTA() {
        return desplegarResultadosJTA;
    }

    /**
     * @return the diasCapitalizacionJTextF
     */
    public javax.swing.JTextField getDiasCapitalizacionJTextF() {
        return diasCapitalizacionJTextF;
    }

    /**
     * @return the diasPagosJTextF
     */
    public javax.swing.JTextField getDiasPagosJTextF() {
        return diasPagosJTextF;
    }

    /**
     * @return the diasPosterioresJTextF
     */
    public javax.swing.JTextField getDiasPosterioresJTextF() {
        return diasPosterioresJTextF;
    }

    /**
     * @return the diasVencidosJTextF
     */
    public javax.swing.JTextField getDiasVencidosJTextF() {
        return diasVencidosJTextF;
    }

    /**
     * @return the doctoFocalJTextF
     */
    public javax.swing.JTextField getDoctoFocalJTextF() {
        return doctoFocalJTextF;
    }

    /**
     * @return the doctosPosterioresJTextF
     */
    public javax.swing.JTextField getDoctosPosterioresJTextF() {
        return doctosPosterioresJTextF;
    }

    /**
     * @return the doctosPreviosJTextF
     */
    public javax.swing.JTextField getDoctosPreviosJTextF() {
        return doctosPreviosJTextF;
    }

    /**
     * @return the interesVenJTextF
     */
    public javax.swing.JTextField getInteresVenJTextF() {
        return interesVenJTextF;
    }

    /**
     * @return the interesVeoPosteriorJTextF
     */
    public javax.swing.JTextField getInteresVeoPosteriorJTextF() {
        return interesVeoPosteriorJTextF;
    }

    /**
     * @return the interesVeoPrevioJTextF
     */
    public javax.swing.JTextField getInteresVeoPrevioJTextF() {
        return interesVeoPrevioJTextF;
    }

    /**
     * @return the tipoInteresJCB
     */
    public javax.swing.JComboBox getTipoInteresJCB() {
        return tipoInteresJCB;
    }

   
}
