/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadorareestructuracion;



/**
 *
 * @author Edgar
 */
public class VentanaPortada extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPortada
     */
    public VentanaPortada() {
        PanelPortada p = new PanelPortada();
        this.setContentPane(p);
        this.setResizable(false);
        this.setLocation(400, 150);
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        calculadoraMenuItem = new javax.swing.JMenuItem();
        creditosMenuItem = new javax.swing.JMenuItem();
        salirMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Reestructuración");

        jMenu1.setText("Calculadora");

        calculadoraMenuItem.setText("Iniciar calculadora");
        calculadoraMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculadoraMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(calculadoraMenuItem);

        creditosMenuItem.setText("Créditos");
        creditosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditosMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(creditosMenuItem);

        salirMenuItem.setText("Salir");
        salirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(salirMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculadoraMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadoraMenuItemActionPerformed
        VentanaReestructuracion f = new VentanaReestructuracion();
        f.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_calculadoraMenuItemActionPerformed

    private void salirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMenuItemActionPerformed

    private void creditosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditosMenuItemActionPerformed
        Creditos creditos = new Creditos();
    }//GEN-LAST:event_creditosMenuItemActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem calculadoraMenuItem;
    private javax.swing.JMenuItem creditosMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem salirMenuItem;
    // End of variables declaration//GEN-END:variables
}
